### ISSUE TITLE
Bugs known before alpha release

### ISSUE THREAD

**Issue by matnrb** [Superlight-Labs/NewFinance#83]
- [x] Add screen for notice when something isn't implemented yet
     - [x] show this notice anywhere when it isn't implemented yet (change mail, tag name, ens name, price notifier, buy/sell, add funds) or remove the element
- [x]  snackbar is shown behind modals - should be in front
- [x] disable currency picker and use eur everywhere for now
- [x] textinputs are not full width (flex in parent container should fix it)
- [x] disable backup until full release and show seed instead
- [ ] display seed when creating wallet
- [x] sending error caused by different currencies used
- [x] pocket refresh buggy (both in overview and inside pocket)
- [x] add key prop warning
- [ ] add some kind of error handling when server is not reachable
- [x] sent transactions are not shown in transaction history

*** _add more when noticing a bug_

- [ ] recieve screen buttons have no feedback. 
- [x] Android: On Setup wallet balance says "Ungültige Zahl"
- [x] Android: Recieve screen cannot be closed
- [x] Android: App icon missing
- [x] Android: input color is white
- [ ] Initial setup flaky (test with prod release)

**Comment by lauhon** [comment]
Currency Picker -> I don't wanna show euro as default. Limits usability to EU citizens, we don't have to enforce that rn. Lets just use BTC

**Comment by matnrb** [comment]
> Currency Picker -> Im against showing euro as default. Limits usability to EU citizens, we don't have to enforce that rn. Lets just use BTC

We have to use at least one currency, because otherwise all of the shown prices would not make sense - see graph or percentage change.

**Comment by matnrb** [comment]
> > Currency Picker -> Im against showing euro as default. Limits usability to EU citizens, we don't have to enforce that rn. Lets just use BTC
> 
> We have to use at least one currency, because otherwise all of the shown prices would not make sense - see graph or percentage change.

fixed

**Comment by matnrb** [comment]
_snackbar is shown behind modals - should be in front_

fixed with a workaround for now - added additional snackbar in modal where its needed.

The problem is, that a modal with react navigation is always in front and the snackbar has to be inside the modal to be shown on top of it.

**Comment by matnrb** [comment]
> _snackbar is shown behind modals - should be in front_
> 
> fixed with a workaround for now - added additional snackbar in modal where its needed.
> 
> The problem is, that a modal with react navigation is always in front and the snackbar has to be inside the modal to be shown on top of it.

Fixed
